### ISSUE TITLE
Option name only accept lowercase

### ISSUE THREAD

**Issue by fjborquez** [TomerRon/cordless#38]
According to [Discord documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure), the restriction of the option name is to have a length of 1-32 characters.
But when I named it with a camelcase string, eg: personName, it throw an exception.
Is this the expected behaviour?
This issue is related to the file and line below.

https://github.com/TomerRon/cordless/blob/afcdd4e14be26472a1d6da08b0af311c48606f83/src/commands/builders/buildOptions.ts#L26

**Comment by TomerRon** [comment]
Hi @fjborquez , yeah this is the expected behavior, since Discord only allows lowercase letters in command names and option names. The exception is either thrown by Discord.js or by the Discord API itself.

See [Application Command Naming](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-naming):

```
If there is a lowercase variant of any letters used, you must use those.
```

This is a roundabout way of saying "no uppercase letters allowed".

We can solve it on our end by lowercasing any given command/option name on initialization, but I don't really want to go that route, since it will introduce other problems.

**Comment by fjborquez** [comment]
Ohh you're right, I didn't notice that :(. Thanks!
